options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker' #image prebuild oleh google
    args: ['build', '-t', 'gcr.io/automated-axis-428810-n4/fastapi-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/automated-axis-428810-n4/fastapi-app:latest']

images:
  - 'gcr.io/automated-axis-428810-n4/fastapi-app:latest'
